### ISSUE TITLE
Ability to render natively in node.js

### ISSUE THREAD

**Issue by YouTube-101** [UnrulyJuli3/nopus-renderer#1]
Hello there,

This is not a bug report but a "feature" request.
When I looked at the code, it seems like it's launching a web browser to the rendering page and running commands to make the rendered audio file in the web browser. This might like it could be the easiest way to get the renderer running on node.js, but it's highly inefficient. Sure, it runs fine on my windows laptop which takes **16 seconds** to render a 96 second song (2 players), but I'm trying to run this on my raspi because it's always on. On my raspi, **it takes 106 seconds** to render the same song. Running a heavy browser that doesn't utilize the computer's capabilities just to render audio is pretty slow for my small computer.

**For efficiency purposes, could you make the renderer code work without opening up a browser or any program that doesn't utilize the computer's processing power?**

It could even try making ffmpeg scripts that ffmpeg could use. Or another solution could be better. Rendering a 96 second song in 106 seconds isn't ideal for someone to wait through and even longer and more complex renders with more players could make the game cancel the render because of the timeout.

If you have any questions, please let me know.

Thanks and have a nice day.

**Comment by UnrulyJuli3** [comment]
This is actually how Jackbox does it on their servers. They do it a little differently, using a different tab to render each player performance, but they use Puppeteer and they do it on a Node server.
This is necessary because the instrument library only runs in a browser. It may eventually be possible to render instruments natively in Node*, but for now the only way to truly render performances properly is using a browser instance.

*I was able to get a Web Audio API Rust implementation to work with the instrument renderer natively on Node once, but it was a little bit buggy and did not work with my service provider.
